export default {
  data() {
    return {
      positionsArray: [
        { label: "EP", value: 0 },
        { label: "MP", value: 1 },
        { label: "CO", value: 2 },
        { label: "BTN", value: 3 },
        { label: "SB", value: 4 },
      ],
      simpleSuitednessArray: [
        { label: "Double Suited", value: "ds" },
        { label: "Single Suited", value: "ss" },
        { label: "Three to suit", value: "3s" },
        { label: "Four to suit", value: "4s" },
        { label: "Rainbow", value: "rb" },
      ],
      showdownCardsArray: [
        { label: "AA", value: "AA" },
        { label: "AK", value: "AK" },
        { label: "AQ", value: "AQ" },
        { label: "AJ", value: "AJ" },
        { label: "AT", value: "AT" },
        { label: "A9", value: "A9" },
        { label: "A8", value: "A8" },
        { label: "A7", value: "A7" },
        { label: "A6", value: "A6" },
        { label: "A5", value: "A5" },
        { label: "A4", value: "A4" },
        { label: "A3", value: "A3" },
        { label: "A2", value: "A2" },
        { label: "KK", value: "KK" },
        { label: "KQ", value: "KQ" },
        { label: "KJ", value: "KJ" },
        { label: "KT", value: "KT" },
        { label: "K9", value: "K9" },
        { label: "K8", value: "K8" },
        { label: "K7", value: "K7" },
        { label: "K6", value: "K6" },
        { label: "K5", value: "K5" },
        { label: "K4", value: "K4" },
        { label: "K3", value: "K3" },
        { label: "K2", value: "K2" },
        { label: "QQ", value: "QQ" },
        { label: "QJ", value: "QJ" },
        { label: "QT", value: "QT" },
        { label: "Q9", value: "Q9" },
        { label: "Q8", value: "Q8" },
        { label: "Q7", value: "Q7" },
        { label: "Q6", value: "Q6" },
        { label: "Q5", value: "Q5" },
        { label: "Q4", value: "Q4" },
        { label: "Q3", value: "Q3" },
        { label: "Q2", value: "Q2" },
        { label: "JJ", value: "JJ" },
        { label: "JT", value: "JT" },
        { label: "J9", value: "J9" },
        { label: "J8", value: "J8" },
        { label: "J7", value: "J7" },
        { label: "J6", value: "J6" },
        { label: "J5", value: "J5" },
        { label: "J4", value: "J4" },
        { label: "J3", value: "J3" },
        { label: "J2", value: "J2" },
        { label: "TT", value: "TT" },
        { label: "T9", value: "T9" },
        { label: "T8", value: "T8" },
        { label: "T7", value: "T7" },
        { label: "T6", value: "T6" },
        { label: "T5", value: "T5" },
        { label: "T4", value: "T4" },
        { label: "T3", value: "T3" },
        { label: "T2", value: "T2" },
        { label: "99", value: "99" },
        { label: "98", value: "98" },
        { label: "97", value: "97" },
        { label: "96", value: "96" },
        { label: "95", value: "95" },
        { label: "94", value: "94" },
        { label: "93", value: "93" },
        { label: "92", value: "92" },
        { label: "88", value: "88" },
        { label: "87", value: "87" },
        { label: "86", value: "86" },
        { label: "85", value: "85" },
        { label: "84", value: "84" },
        { label: "83", value: "83" },
        { label: "82", value: "82" },
        { label: "77", value: "77" },
        { label: "76", value: "76" },
        { label: "75", value: "75" },
        { label: "74", value: "74" },
        { label: "73", value: "73" },
        { label: "72", value: "72" },
        { label: "66", value: "66" },
        { label: "65", value: "65" },
        { label: "64", value: "64" },
        { label: "63", value: "63" },
        { label: "62", value: "62" },
        { label: "55", value: "55" },
        { label: "54", value: "54" },
        { label: "53", value: "53" },
        { label: "52", value: "52" },
        { label: "44", value: "44" },
        { label: "43", value: "43" },
        { label: "42", value: "42" },
        { label: "33", value: "33" },
        { label: "32", value: "32" },
        { label: "22", value: "22" },
      ],
      detailedSuitednessArray: [
        { label: "wxwx", value: "wxwx" },
        { label: "wxxw", value: "wxxw" },
        { label: "wwxy", value: "wwxy" },
        { label: "wxwy", value: "wxwy" },
        { label: "wxxy", value: "wxxy" },
        { label: "wxyw", value: "wxyw" },
        { label: "wxyx", value: "wxyx" },
        { label: "wxyy", value: "wxyy" },
        { label: "wwwx", value: "wwwx" },
        { label: "wwxw", value: "wwxw" },
        { label: "wxww", value: "wxww" },
        { label: "wxxx", value: "wxxx" },
        { label: "wwww", value: "wwww" },
        { label: "wxyz", value: "wxyz" },
      ],
      simpleDetailArray: {
        ds: ["wxwx", "wxxw"], // 'wwxx'
        ss: ["wwxy", "wxwy", "wxxy", "wxyw", "wxyx", "wxyy"],
        "3s": ["wwwx", "wwxw", "wxww", "wxxx"],
        "4s": ["wwww"],
        rb: ["wxyz"],
      },
    };
  },
};
